window:
  decorations: none
  opacity: 0.98
  padding:
    x: 5
    y: 5

shell:
  program: /usr/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

font:
  normal:
    family: Iosevka
  size: 13

env:
  TERM: xterm-256color

import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
#
#colors:
#  primary:
#    background: '#1a1b26'
#    foreground: '#c0caf5'
