import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Iosevka"

[shell]
args = ["-l", "-c", "tmux attach || tmux new zsh"]
program = "zsh"

[window]
decorations = "none"
opacity = 0.85

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
  {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
  {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
  {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
  {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
  {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
  {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
  {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
  {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
  {key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]

